// SPDX-License-Identifier: Apache-2.0
// GENERATED by scripts/generate_semantics.py; DO NOT EDIT.
// normalized catalog sha256: fbadcad47d75a3b5b54a7c3a62066888cdfa342b5f1498ebfee4e5435e98f3f0
`timescale 1ns / 1ps
`default_nettype none

module autoisa_ci_semantic_engine (
    input wire [7:0] ci_id_i,
    input wire [5:0][31:0] operands_i,
    input wire [31:0] immediate_i,
    output logic supported_o,
    output logic [4:0] latency_o,
    output logic [1:0] result_valid_o,
    output logic [1:0][31:0] results_o
);

  logic [31:0] d0_sum;
  logic [31:0] d1_product;
  logic [31:0] d1_result;
  logic [31:0] d2_product;
  logic [31:0] d2_sum;
  logic [31:0] d2_result;
  logic [31:0] d3_sum;
  logic [31:0] d3_difference;
  logic [31:0] d4_ac;
  logic [31:0] d4_bd;
  logic [31:0] d4_ad;
  logic [31:0] d4_bc;
  logic [31:0] d4_real;
  logic [31:0] d4_imag;
  logic [31:0] d5_s01;
  logic [31:0] d5_s23;
  logic [31:0] d5_s45;
  logic [31:0] d5_s0123;
  logic [31:0] d5_result;
  logic [31:0] d6_ab;
  logic [31:0] d6_cd;
  logic [31:0] d6_ef;
  logic [31:0] d6_sum_ab_cd;
  logic [31:0] d6_diff_ab_cd;
  logic [31:0] d6_sum;
  logic [31:0] d6_difference;
  logic [31:0] d7_shifted;
  logic [31:0] d7_biased;
  logic [31:0] d7_result;

  always_comb begin
    supported_o = 1'b0;
    latency_o = 5'd1;
    result_valid_o = 2'b00;
    results_o = '0;
    d0_sum = '0;
    d1_product = '0;
    d1_result = '0;
    d2_product = '0;
    d2_sum = '0;
    d2_result = '0;
    d3_sum = '0;
    d3_difference = '0;
    d4_ac = '0;
    d4_bd = '0;
    d4_ad = '0;
    d4_bc = '0;
    d4_real = '0;
    d4_imag = '0;
    d5_s01 = '0;
    d5_s23 = '0;
    d5_s45 = '0;
    d5_s0123 = '0;
    d5_result = '0;
    d6_ab = '0;
    d6_cd = '0;
    d6_ef = '0;
    d6_sum_ab_cd = '0;
    d6_diff_ab_cd = '0;
    d6_sum = '0;
    d6_difference = '0;
    d7_shifted = '0;
    d7_biased = '0;
    d7_result = '0;
    unique case (ci_id_i)
      8'd0: begin
        supported_o = 1'b1;
        latency_o = 5'd1;
        result_valid_o = 2'b01;
        d0_sum = operands_i[0] + operands_i[1];
        results_o[0] = d0_sum;
      end
      8'd1: begin
        supported_o = 1'b1;
        latency_o = 5'd2;
        result_valid_o = 2'b01;
        d1_product = operands_i[0] * operands_i[1];
        d1_result = d1_product + operands_i[2];
        results_o[0] = d1_result;
      end
      8'd2: begin
        supported_o = 1'b1;
        latency_o = 5'd3;
        result_valid_o = 2'b01;
        d2_product = operands_i[0] * operands_i[1];
        d2_sum = d2_product + operands_i[2];
        d2_result = d2_sum ^ operands_i[3];
        results_o[0] = d2_result;
      end
      8'd3: begin
        supported_o = 1'b1;
        latency_o = 5'd2;
        result_valid_o = 2'b11;
        d3_sum = operands_i[0] + operands_i[1];
        d3_difference = operands_i[0] - operands_i[1];
        results_o[0] = d3_sum;
        results_o[1] = d3_difference;
      end
      8'd4: begin
        supported_o = 1'b1;
        latency_o = 5'd4;
        result_valid_o = 2'b11;
        d4_ac = operands_i[0] * operands_i[2];
        d4_bd = operands_i[1] * operands_i[3];
        d4_ad = operands_i[0] * operands_i[3];
        d4_bc = operands_i[1] * operands_i[2];
        d4_real = d4_ac - d4_bd;
        d4_imag = d4_ad + d4_bc;
        results_o[0] = d4_real;
        results_o[1] = d4_imag;
      end
      8'd5: begin
        supported_o = 1'b1;
        latency_o = 5'd3;
        result_valid_o = 2'b01;
        d5_s01 = operands_i[0] + operands_i[1];
        d5_s23 = operands_i[2] + operands_i[3];
        d5_s45 = operands_i[4] + operands_i[5];
        d5_s0123 = d5_s01 + d5_s23;
        d5_result = d5_s0123 + d5_s45;
        results_o[0] = d5_result;
      end
      8'd6: begin
        supported_o = 1'b1;
        latency_o = 5'd5;
        result_valid_o = 2'b11;
        d6_ab = operands_i[0] * operands_i[1];
        d6_cd = operands_i[2] * operands_i[3];
        d6_ef = operands_i[4] * operands_i[5];
        d6_sum_ab_cd = d6_ab + d6_cd;
        d6_diff_ab_cd = d6_ab - d6_cd;
        d6_sum = d6_sum_ab_cd + d6_ef;
        d6_difference = d6_diff_ab_cd + d6_ef;
        results_o[0] = d6_sum;
        results_o[1] = d6_difference;
      end
      8'd7: begin
        supported_o = 1'b1;
        latency_o = 5'd1;
        result_valid_o = 2'b01;
        d7_shifted = operands_i[0] << immediate_i[4:0];
        d7_biased = operands_i[1] + immediate_i;
        d7_result = d7_shifted ^ d7_biased;
        results_o[0] = d7_result;
      end
      default: begin
      end
    endcase
  end

endmodule

`default_nettype wire
