// Generated by scripts/generate_layout_decoder.py; do not edit.
`timescale 1ns/1ps
`default_nettype none
module autoisa_ci_layout_decoder #(
    parameter int unsigned MAX_SRC = 4,
    parameter int unsigned MAX_DST = 2
) (
    input  logic [31:0] instr_i,
    output logic        valid_o,
    output logic        illegal_o,
    output logic [2:0]  layout_id_o,
    output logic [6:0]  semantic_id_o,
    output logic [MAX_SRC-1:0] src_valid_o,
    output logic [MAX_SRC-1:0][4:0] src_addr_o,
    output logic [MAX_DST-1:0] dst_valid_o,
    output logic [MAX_DST-1:0][4:0] dst_addr_o,
    output logic [31:0] immediate_o,
    output logic [2:0]  memory_profile_o,
    output logic        pair_constrained_o
);

  localparam logic [6:0] CUSTOM_OPCODE = 7'h5b;

  always_comb begin
    valid_o            = 1'b0;
    illegal_o          = 1'b0;
    layout_id_o        = '0;
    semantic_id_o      = '0;
    src_valid_o        = '0;
    src_addr_o         = '0;
    dst_valid_o        = '0;
    dst_addr_o         = '0;
    immediate_o        = '0;
    memory_profile_o   = '0;
    pair_constrained_o = 1'b0;

    if (instr_i[6:0] == CUSTOM_OPCODE) begin
      valid_o     = 1'b1;
      layout_id_o = instr_i[9:7];
      unique case (instr_i[9:7])
        3'd0: begin : decode_l0_2r1w_gpr32
          semantic_id_o    = instr_i[31:25];
          immediate_o      = 32'b0;
          memory_profile_o = 3'd0;
          src_valid_o[0] = 1'b1;
          src_addr_o[0]  = instr_i[19:15];
          src_valid_o[1] = 1'b1;
          src_addr_o[1]  = instr_i[24:20];
          dst_valid_o[0] = 1'b1;
          dst_addr_o[0]  = instr_i[14:10];
        end
        3'd1: begin : decode_l1_3r1w_gpr32
          semantic_id_o    = {5'b0, instr_i[31:30]};
          immediate_o      = 32'b0;
          memory_profile_o = 3'd0;
          src_valid_o[0] = 1'b1;
          src_addr_o[0]  = instr_i[19:15];
          src_valid_o[1] = 1'b1;
          src_addr_o[1]  = instr_i[24:20];
          src_valid_o[2] = 1'b1;
          src_addr_o[2]  = instr_i[29:25];
          dst_valid_o[0] = 1'b1;
          dst_addr_o[0]  = instr_i[14:10];
        end
        3'd2: begin : decode_l2_4r1w_rvc8
          semantic_id_o    = instr_i[31:25];
          immediate_o      = 32'b0;
          memory_profile_o = 3'd0;
          src_valid_o[0] = 1'b1;
          src_addr_o[0]  = {2'b01, instr_i[15:13]};
          src_valid_o[1] = 1'b1;
          src_addr_o[1]  = {2'b01, instr_i[18:16]};
          src_valid_o[2] = 1'b1;
          src_addr_o[2]  = {2'b01, instr_i[21:19]};
          src_valid_o[3] = 1'b1;
          src_addr_o[3]  = {2'b01, instr_i[24:22]};
          dst_valid_o[0] = 1'b1;
          dst_addr_o[0]  = {2'b01, instr_i[12:10]};
        end
        3'd3: begin : decode_l3_2r2w_pair
          semantic_id_o    = instr_i[31:25];
          immediate_o      = 32'b0;
          memory_profile_o = 3'd0;
          src_valid_o[0] = 1'b1;
          src_addr_o[0]  = instr_i[19:15];
          src_valid_o[1] = 1'b1;
          src_addr_o[1]  = instr_i[24:20];
          dst_valid_o[0] = 1'b1;
          dst_addr_o[0]  = instr_i[14:10];
          pair_constrained_o = 1'b1;
          dst_valid_o[1]       = 1'b1;
          dst_addr_o[1]        = dst_addr_o[0] + 5'd1;
          if ((dst_addr_o[0] == 5'd0) || dst_addr_o[0][0] ||
              (dst_addr_o[0] == 5'd31)) begin
            illegal_o = 1'b1;
          end
        end
        3'd4: begin : decode_m1_host_load
          semantic_id_o    = 7'd0;
          immediate_o      = {{20{instr_i[31]}}, instr_i[31:20]};
          memory_profile_o = 3'd1;
          src_valid_o[0] = 1'b1;
          src_addr_o[0]  = instr_i[19:15];
          dst_valid_o[0] = 1'b1;
          dst_addr_o[0]  = instr_i[14:10];
        end
        3'd5: begin : decode_m1_host_load_add
          semantic_id_o    = 7'd1;
          immediate_o      = {{25{instr_i[31]}}, instr_i[31:25]};
          memory_profile_o = 3'd2;
          src_valid_o[0] = 1'b1;
          src_addr_o[0]  = instr_i[19:15];
          src_valid_o[1] = 1'b1;
          src_addr_o[1]  = instr_i[24:20];
          dst_valid_o[0] = 1'b1;
          dst_addr_o[0]  = instr_i[14:10];
        end
        3'd6: begin : decode_m1_host_ldd_pair
          semantic_id_o    = 7'd2;
          immediate_o      = {{20{instr_i[31]}}, instr_i[31:20]};
          memory_profile_o = 3'd3;
          src_valid_o[0] = 1'b1;
          src_addr_o[0]  = instr_i[19:15];
          dst_valid_o[0] = 1'b1;
          dst_addr_o[0]  = instr_i[14:10];
          pair_constrained_o = 1'b1;
          dst_valid_o[1]       = 1'b1;
          dst_addr_o[1]        = dst_addr_o[0] + 5'd1;
          if ((dst_addr_o[0] == 5'd0) || dst_addr_o[0][0] ||
              (dst_addr_o[0] == 5'd31)) begin
            illegal_o = 1'b1;
          end
        end
        default: begin
          illegal_o = 1'b1;
        end
      endcase
    end
  end

  always_comb begin : check_illegal_implies_valid
    assert (!(illegal_o && !valid_o))
      else $error("illegal_o requires a recognized custom opcode");
  end

endmodule
`default_nettype wire
